---
# tasks file for redmine_my_page_queries
- name: Migrate db
  command: bundle exec rake my_page_queries:upgrade
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: "{{ RAILS_ENV }}"
  sudo_user: "{{ sudo_user }}"
